// What the linter holds the code to: mistakes, not taste. (Layout is the formatter's:
// .prettierrc.) Run it with `npm run lint`.
//
// Written out rather than taken from a preset, so that it needs nothing but eslint itself
// and every rule here is one somebody chose.
const node = [
  'process',
  'console',
  'Buffer',
  'URL',
  'URLSearchParams',
  'setTimeout',
  'clearTimeout',
  'setInterval',
  'clearInterval',
  'setImmediate',
  'clearImmediate',
  'queueMicrotask',
  'fetch',
  'AbortSignal',
  'AbortController',
  'TextDecoder',
  'TextEncoder',
  'structuredClone',
  'globalThis',
  'Atomics',
  'SharedArrayBuffer',
  'Intl',
  'performance',
  'Response',
  'Request',
  'Headers',
  'FormData',
  'Blob',
  'crypto',
  'navigator',
  'WebSocket',
];

export default [
  { ignores: ['node_modules/**', 'data/**', 'user-plugins/**', 'agent/**'] },
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: Object.fromEntries(node.map((n) => [n, 'readonly'])) },
    linterOptions: { reportUnusedDisableDirectives: 'error' },
    rules: {
      // ---- things that are wrong
      'no-undef': 'error',
      'no-unused-vars': [
        'error',
        { args: 'after-used', argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none', ignoreRestSiblings: true },
      ],
      'no-const-assign': 'error',
      'no-dupe-keys': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-import-assign': 'error',
      'no-redeclare': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-async-promise-executor': 'error',
      'no-cond-assign': ['error', 'except-parens'],
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-constant-binary-expression': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-obj-calls': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unused-private-class-members': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'getter-return': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      // ---- things that hide what is wrong
      'no-var': 'error',
      'prefer-const': ['error', { destructuring: 'all' }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-throw-literal': 'error',
      'no-useless-escape': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-prototype-builtins': 'error',
      'no-shadow-restricted-names': 'error',
      'no-template-curly-in-string': 'error',
    },
  },
  // Tests: what node:test gives them.
  { files: ['test/**'], rules: { 'no-template-curly-in-string': 'off' } },
];
